NikolasKaplan1/prog2-25-C2

requirements.txt
src/controlador.py
src/ejemplos.py
src/models/accion.py
src/models/mercado.py

He documentado mucho más el código en controlador, ejemplos, accion y mercado. En controlador falta por comentar la parte de los inversores y las transacciones y en ejemplos la parte de transacciones (esto debe hacerlo Niko ya que es su parte). En requirements.txt he puesto el pandas.

Docstrings, sugerencia de tipos y requirements

---

src/models/accion.py

He mejorado en la documentación y he añadido sobrecarga de operadores como let y gt, así como atributos privados y protegidos.

Cambios en la clase Accion y AccionReal

---

src/models/mercado.py

He mejorado la documentación, añadido sobrecarga de operadores (len, contains, iter...) así como atributos privados y protegidos. También he añadido una clase abstracta por si se decidiese crear más mercados, que todos deban tener una clases obligatorias.

Cambios en mercado

---

src/ejemplos.py

Mejora de la documentación y, debido a los cambios en el controlador, he tenido que añadir nuevas funciones.

Cambios en ejemplos

---

src/controlador.py

Mejora de la documentación y adaptación a los cambios creados en mercado y accion añadiendo nuevas funciones.

Cambios en controlador

---

src/models/inversor.py

Incorporación de:
-Encapsulamiento
-Nuevas sobrecargas de operador
-Type hints
-Mejora en la documentación

Mejoras en clase Inversor.

---

src/routers/manejo_archivos.py

He creado el archivo para poder manejar los archivos. Por ahora he creado uno en el que están todas las acciones (exportar_acciones_csv), las acciones reales (exportar_acciones_reakes_csv), uno en el que está el historial de precios (exportar_historial_precios_csv), otro en el que están las acciones cuyas empresas están en bancarrota (exportar_acciones_bancarrota_csv). También hay para mercado: uno en el que están todos los mercados (exportar_mercados_csv) y otro en el que están las acciones por mercado (acciones_por_mercado_csv). Además, hay archivos pickle para guardar las acciones, el historial de precios y los mercados. En todos ellos falta la documentación.

Creación del archivo para manejar los archivos

---

src/models/transaccion.py

- Añadidos type hints en todos los métodos.
- Documentación mejorada con docstrings detallados.
- Aplicado de encapsulamiento protegido a _fecha_hora para restringir modificaciones directas.
- Implementada sobrecarga del operador __getitem__ para acceso tipo diccionario a atributos clave

Mejoras en Transaccion.py

---

src/routers/manejo_archivos.py

- Añadidas funciones de importacion desde Pickle.
- Exportar lista de inversores y transacciones hacia archivos CSV.
- Documentación detallada en todos los métodos añadidos.

Ampliación manejo_archivos.py

---

src/ejemplos.py

- Añadidas funciones para verificar las acciones de un inversor y comparar inversores (para ver si tienen carteras similares).
- Añadida función para consultar un campo específico de una transacción.
- Incorporadas las tres funciones al menú principal.

Funciones añadidas a examples.py.

---

src/routers/manejo_archivos.py

He hecho mejoras en la documentación de varias funciones (por ejemplo, ruta ahora es tipo Path) y he restaurado las funciones exportar_acciones_reales_csv, exportar_acciones_bancarrota_csv, acciones_por_mercado_csv, exportar_acciones_pickle, exportar_historiales_pickle y exportar_mercados_registrados_pickle

Actualización en manejo_archivos

---

src/routers/manejo_archivos.py

He añadido las funciones para importar los archivos pickle y arreglado un error de documentacion mio en importar_inversor_pickle (habia puesto -> list[Inversor] -> None)

Añadido de funciones

---

src/models/accion.py

He hecho algunos cambios que hacían que no funcionase las cosas bien como pone Accion en vez de 'Accion' en el type hints o poner precio_actual en lugar de _precio_actual.

Modificaciones ligeras en accion.py

---

src/routers/manejo_archivos.py

He hecho algunos cambios en manejo_archivos.py porque he cambiado algunos registros a privados en otros archivos que hacía que hubiesen errores aquí.

Actualización manejo archivos

---

src/controlador.py

He puesto algunos espacios para que quede mejor y he cambiado cosas para que todo funcione correctamente.

Cambios en controlador.py

---

src/routers/manejo_archivos.py

He cambiado algunos atributos que estaban en público y los había puesto en privado.

Cambios en manejo_archivos.py

---

src/models/models.py

He puesto __table_args__ = {"extend_existing": True} porque daba error.

Actualización models.py

---

src/models/mercado.py

He mejorado la doumentación de str y he añadido el método de eliminar_accion.

Cambios en mercado.py

---

src/controlador.py

He hecho un pequeño cambio en la documentación del controlador.

Cambios documentación controlador

---

src/controlador.py

Arreglos en controlador

---

src/models/mercado.py

Arreglo de mercado.py

---

src/ejemplos.py

He cambiado el print en eliminar_accion porque salia mal

Cambio en ejemplos.py

---

src/models/mercado.py

Mejoras en la documentación de mercado.py

Documentación mercado.py

---

src/estrategias/ia.py
src/estrategias/inversor_agresivo.py
src/estrategias/inversor_conservador.py

Añadido docstrings y type hints detallados en ambas subclases de Inversor.

Documentación completa clases InversorConservador e InversorAgresivo

---

src/controlador.py

Ajustes necesarios para el correcto funcionamiento del menú.

modifico controlador.py

---

src/models/transaccion.py

Para el correcto funcionamiento del menú.

modifico transaccion.py

---

src/models/inversor.py

Modificaciones en Inversor, para el funcionamiento del menú.

Modifico Inversor.py

---

src/models/transaccion.py

cambios finales en transaccion.py

Feature transaccion

---

src/database/schema.sql

he vuelto a poner el schema.sql

schema.sql

---

requirements.txt

he puesto == porque antes estaba =

error en requirements.txt

---

src/controlador.py

he cambiado la funcion de la recomendacion para que se base en la ia.

cambio en la funcion de la recomendacion

---

src/estrategias/ia.py

he cambiado algunos atributos a privado y he añadido un error por si no hay acciones registradas.

cambios en ia.py

---

src/models/inversor.py

había dos librerias que se importaban dos veces

cambios en inversor.py
